### ISSUE TITLE
Fix dynamic timestamp in transaction messages

### ISSUE THREAD

**Issue by TymonMarek** [TymonMarek/discord-bot#10]
## Issue
Transaction messages with timestamps usually show incorrect dates.
![image](https://github.com/TymonMarek/discord-bot/assets/117597583/cf3890d0-a812-4ac0-874b-4313e9ccc903)

## File 
https://github.com/TymonMarek/discord-bot/blob/2e70fd3dfd8482b082a638098ebc0cdf2f70266a/src/commands/economy/Bank.Transfer.ts#L140C1-L141C1

**Comment by DaPandamonium** [comment]
Probably to update like this.

```js
    } <t:${Math.floor(new Date().getTime() / 1000)}:R>`
```
